# Generated by Django 2.1 on 2021-03-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp1', '0002_auto_20210311_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title_Name '),
        ),
    ]
