# Generated by Django 2.1 on 2021-03-11 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp1', '0003_auto_20210311_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='titlee',
        ),
    ]
