# Generated by Django 2.1 on 2021-03-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp1', '0004_auto_20210311_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='titlee',
            new_name='title',
        ),
    ]
