# Generated by Django 2.1 on 2021-03-12 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newapp1', '0006_todo_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='a',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='b',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
